#!/usr/bin/env python3
"""Deterministic map of what this repository contains and how its parts relate.

Two jobs. It gives a reader an accurate index of components and relations without
reading every file, and it gives CI a drift check: `--check` recomputes the manifest
and fails if the committed one no longer matches the tree. A map that quietly goes
stale is worse than no map, because people trust it.

Adapted from the architecture-explorer manifest in reallaksh19/Common PR #395. The
component taxonomy here is this repository's own.
"""
from __future__ import annotations

import argparse
import ast
import hashlib
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
if __package__ in (None, ""):
    sys.path.insert(0, str(REPO))

from Shared.tools import build_web_data  # noqa: E402

MANIFEST = REPO / "docs" / "architecture-manifest.json"

ROLES = [
    ("Shared/publication_host", "ENGINE", "Subject-neutral publication engine"),
    ("Shared/library", "LIBRARY", "Topic library: intake, resolution, promotion, compilation"),
    ("Shared/gates", "GATES", "Technical gate schema and validator"),
    ("Shared/roles", "CONTRACT", "The six Core role specifications"),
    ("Shared/tools", "TOOLING", "Guardrails and generators"),
    ("tests", "TEST", "Executable checks"),
    ("tools", "WEB", "Browsable surfaces over generated data"),
]
SUBJECT_ROLES = [
    ("adapter", "ADAPTER", "Subject contract, calculation owner and scenes"),
    ("gates", "GATE_DATA", "Subject gate registry and curriculum bindings"),
    ("library", "LIBRARY_DATA", "Subject library packages"),
    ("content", "CONTENT", "Authored runs and published products"),
]
SKIP_PARTS = {"__pycache__", ".git", "publication"}


def subjects() -> list[str]:
    return sorted(p.parent.name for p in REPO.glob("*/adapter/CoreContracts.json"))


def classify(path: Path) -> tuple[str, str] | None:
    relative = path.relative_to(REPO).as_posix()
    for prefix, role, description in ROLES:
        if relative.startswith(prefix + "/") or relative == prefix:
            return role, description
    parts = relative.split("/")
    if len(parts) > 2 and parts[0] in subjects():
        for folder, role, description in SUBJECT_ROLES:
            if parts[1] == folder:
                return role, description
    return None


def python_relations(path: Path, relative: str) -> list[dict]:
    """Import edges between this repository's own modules."""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except (SyntaxError, UnicodeDecodeError):
        return []
    found = []
    for node in ast.walk(tree):
        module = None
        if isinstance(node, ast.ImportFrom) and node.module:
            module = node.module
        elif isinstance(node, ast.Import):
            module = node.names[0].name
        if module and module.split(".")[0] in {"Shared", *subjects()}:
            found.append({"from": relative, "to": module, "kind": "IMPORTS"})
    return found


def collect() -> dict:
    # The manifest hashes every shipped file, and one of them is generated by another
    # tool. Hashing a stale copy would produce a manifest that no regeneration order
    # converges on, so the generated file is brought up to date first rather than the
    # correct order being left for a contributor to guess.
    build_web_data.write()
    components, relations = [], []
    for path in sorted(REPO.rglob("*")):
        if not path.is_file() or any(part in SKIP_PARTS for part in path.relative_to(REPO).parts):
            continue
        if path.suffix not in {".py", ".json", ".md", ".html", ".js", ".css", ".yml"}:
            continue
        classified = classify(path)
        if classified is None:
            continue
        role, description = classified
        relative = path.relative_to(REPO).as_posix()
        components.append({"path": relative, "role": role, "role_description": description,
                           "bytes": path.stat().st_size,
                           "sha256": hashlib.sha256(path.read_bytes()).hexdigest()})
        if path.suffix == ".py":
            relations += python_relations(path, relative)

    by_role: dict[str, int] = {}
    for component in components:
        by_role[component["role"]] = by_role.get(component["role"], 0) + 1
    body = {"components": components, "relations": sorted(
        relations, key=lambda r: (r["from"], r["to"], r["kind"]))}
    return {"schema_version": "1.0.0",
            "subjects": subjects(),
            "component_count": len(components),
            "relation_count": len(body["relations"]),
            "components_by_role": dict(sorted(by_role.items())),
            "digest": "sha256:" + hashlib.sha256(
                json.dumps(body, sort_keys=True, separators=(",", ":")).encode()).hexdigest(),
            **body}


def main() -> int:
    parser = argparse.ArgumentParser(description="Build or verify the architecture manifest")
    parser.add_argument("--check", action="store_true", help="fail if the committed manifest has drifted")
    args = parser.parse_args()
    current = collect()
    if args.check:
        if not MANIFEST.is_file():
            print("no committed manifest; run without --check first")
            return 1
        committed = json.loads(MANIFEST.read_text(encoding="utf-8"))
        if committed.get("digest") != current["digest"]:
            print("architecture manifest has drifted.")
            print(f"  committed {committed.get('digest')}")
            print(f"  current   {current['digest']}")
            was = {c["path"] for c in committed.get("components", [])}
            now = {c["path"] for c in current["components"]}
            for path in sorted(now - was):
                print(f"  + {path}")
            for path in sorted(was - now):
                print(f"  - {path}")
            changed = [c["path"] for c in current["components"]
                       if c["path"] in was
                       and c["sha256"] != next(x["sha256"] for x in committed["components"]
                                               if x["path"] == c["path"])]
            for path in sorted(changed):
                print(f"  ~ {path}")
            print("\nRegenerate with: python3 Shared/tools/build_manifest.py")
            return 1
        print(f"architecture manifest up to date: {current['component_count']} components, "
              f"{current['relation_count']} relations")
        return 0
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(json.dumps(current, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {MANIFEST.relative_to(REPO)}: {current['component_count']} components, "
          f"{current['relation_count']} relations, {current['digest']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
