// Generated by Shared/tools/build_web_data.py -- do not edit by hand.
window.GRADE9V3 = {
  "generated_by": "Shared/tools/build_web_data.py",
  "subjects": {
    "Chemistry": {
      "contract": {
        "learner_products": {
          "CORE1": "EXISTING_BASIC_NOTES",
          "CORE2": "EXISTING_FROZEN_QUESTIONS_AND_HINTS",
          "CORE1A": "DECLARATIVE_STUDY",
          "CORE1B": "CONCEPTUAL_SELF_TUTOR",
          "CORE2A": "SOLUTION_APPRENTICESHIP",
          "CORE2B": "APPLICATION_AND_TRANSFER_TUTOR"
        },
        "validator_catalogue": [
          {
            "id": "PARTICLE_ATOM_COUNT",
            "status": "IMPLEMENTED",
            "shape": "ELEMENT_COUNT_MAP",
            "comparison": "EXACT_INTEGER_MAP_EQUALITY",
            "does_not_prove": "That the declared species are the species actually present, or that the amounts are physically achievable."
          },
          {
            "id": "CONSERVATION_LEDGER",
            "status": "IMPLEMENTED",
            "shape": "CONSERVATION_LEDGER",
            "comparison": "EXACT_INTEGER_MAP_EQUALITY",
            "does_not_prove": "That the reaction occurs, that charge or phase are correct, or that the equation represents a real mechanism."
          },
          {
            "id": "REACTION_EXTENT_COUNTS",
            "status": "IMPLEMENTED",
            "shape": "EXTENT_MAP",
            "comparison": "EXACT_INTEGER_MAP_EQUALITY",
            "does_not_prove": "Equilibrium behaviour, rate, yield, or that the reaction goes to completion in reality."
          }
        ],
        "representation_kinds": [
          {
            "id": "PARTICLE_DIAGRAM",
            "status": "PROPOSED",
            "requires": [
              "declared representation level",
              "particle identity and count",
              "no implied mechanism"
            ]
          },
          {
            "id": "SYMBOLIC_EQUATION",
            "status": "PROPOSED",
            "requires": [
              "subscripts versus coefficients distinguished",
              "charges",
              "phase labels",
              "reaction arrow semantics"
            ]
          },
          {
            "id": "ENERGY_PROFILE",
            "status": "PROPOSED",
            "requires": [
              "declared reference state",
              "axis meaning",
              "no mechanistic claim from a schematic"
            ]
          }
        ],
        "curriculum": {
          "boards": [
            "CBSE"
          ],
          "grades": [
            9,
            10,
            11
          ],
          "tiers": [
            "NOT_IN_JEE",
            "JEE_MAINS",
            "JEE_ADVANCED",
            "BOTH"
          ],
          "binding_authority": "EXACT_REGISTRY_BINDING_REQUIRED",
          "unbound_scope_state": "HELD_INSUFFICIENT_AUTHORITY"
        }
      },
      "gates": [],
      "buckets": [],
      "packages": [],
      "library_available": false
    },
    "Mathematics": {
      "contract": {
        "learner_products": {
          "CORE1": "EXISTING_BASIC_NOTES",
          "CORE2": "EXISTING_FROZEN_QUESTIONS_AND_HINTS",
          "CORE1A": "DECLARATIVE_STUDY",
          "CORE1B": "CONCEPTUAL_SELF_TUTOR",
          "CORE2A": "SOLUTION_APPRENTICESHIP",
          "CORE2B": "APPLICATION_AND_TRANSFER_TUTOR"
        },
        "validator_catalogue": [
          {
            "id": "POLYNOMIAL_FROM_ROOTS",
            "status": "IMPLEMENTED",
            "shape": "EXACT_RATIONAL_COEFFICIENT_LIST",
            "comparison": "EXACT_RATIONAL_EQUALITY",
            "does_not_prove": "That those roots are the roots of the problem's actual polynomial, or that the factorisation was legitimate over the stated domain."
          },
          {
            "id": "POLYNOMIAL_VALUE",
            "status": "IMPLEMENTED",
            "shape": "EXACT_RATIONAL",
            "comparison": "EXACT_RATIONAL_EQUALITY",
            "does_not_prove": "That the point lies in the problem's admissible domain."
          },
          {
            "id": "LINEAR_EQUATION",
            "status": "IMPLEMENTED",
            "shape": "EXACT_RATIONAL",
            "comparison": "EXACT_RATIONAL_EQUALITY",
            "does_not_prove": "That the modelling step producing that equation was correct, or that solutions were not lost earlier by a non-equivalent transformation."
          }
        ],
        "representation_kinds": [
          {
            "id": "GEOMETRIC_CONSTRUCTION",
            "status": "PROPOSED",
            "requires": [
              "declared given/construct/prove split",
              "congruence and parallelism marks",
              "labelled points"
            ]
          },
          {
            "id": "FUNCTION_PLOT",
            "status": "PROPOSED",
            "requires": [
              "domain and range",
              "excluded values marked",
              "asymptotes and discontinuities visible"
            ]
          },
          {
            "id": "NUMBER_LINE",
            "status": "PROPOSED",
            "requires": [
              "open versus closed endpoints",
              "declared direction"
            ]
          }
        ],
        "curriculum": {
          "boards": [
            "CBSE"
          ],
          "grades": [
            9,
            10,
            11
          ],
          "tiers": [
            "NOT_IN_JEE",
            "JEE_MAINS",
            "JEE_ADVANCED",
            "BOTH"
          ],
          "binding_authority": "EXACT_REGISTRY_BINDING_REQUIRED",
          "unbound_scope_state": "HELD_INSUFFICIENT_AUTHORITY"
        }
      },
      "gates": [],
      "buckets": [],
      "packages": [],
      "library_available": false
    },
    "Physics": {
      "contract": {
        "learner_products": {
          "CORE1": "EXISTING_BASIC_NOTES",
          "CORE2": "EXISTING_FROZEN_QUESTIONS_AND_HINTS",
          "CORE1A": "DECLARATIVE_STUDY",
          "CORE1B": "CONCEPTUAL_SELF_TUTOR",
          "CORE2A": "SOLUTION_APPRENTICESHIP",
          "CORE2B": "APPLICATION_AND_TRANSFER_TUTOR"
        },
        "validator_catalogue": [
          {
            "id": "SPEED_FROM_COMPONENTS",
            "status": "IMPLEMENTED",
            "shape": "SCALAR_WITH_UNIT",
            "comparison": "RELATIVE_AND_ABSOLUTE_TOLERANCE_1E-9",
            "does_not_prove": "That the components themselves were derived correctly, or that the frame was chosen correctly."
          },
          {
            "id": "CONSTANT_ACCELERATION_VELOCITY",
            "status": "IMPLEMENTED",
            "shape": "SCALAR_WITH_UNIT",
            "comparison": "RELATIVE_AND_ABSOLUTE_TOLERANCE_1E-9",
            "does_not_prove": "That constant acceleration is the right model for the situation."
          },
          {
            "id": "CONSTANT_ACCELERATION_INITIAL_VELOCITY",
            "status": "IMPLEMENTED",
            "shape": "SCALAR_WITH_UNIT",
            "comparison": "RELATIVE_AND_ABSOLUTE_TOLERANCE_1E-9",
            "does_not_prove": "That constant acceleration is the right model for the situation."
          },
          {
            "id": "CONSTANT_ACCELERATION_EVENT_TIME",
            "status": "IMPLEMENTED",
            "shape": "SCALAR_WITH_UNIT",
            "comparison": "RELATIVE_AND_ABSOLUTE_TOLERANCE_1E-9",
            "does_not_prove": "That the event occurs within the physical situation's validity window."
          },
          {
            "id": "APEX_STATE",
            "status": "IMPLEMENTED",
            "shape": "STRUCTURED_STATE",
            "comparison": "FIELDWISE_TOLERANCE_1E-9",
            "does_not_prove": "That drag is negligible in the described situation."
          }
        ],
        "representation_kinds": [
          {
            "id": "VECTOR",
            "status": "IMPLEMENTED",
            "requires": [
              "frame",
              "axis labels",
              "unit",
              "symbol",
              "equal coordinate scale"
            ]
          },
          {
            "id": "GRAPH",
            "status": "IMPLEMENTED",
            "requires": [
              "strictly increasing x domain",
              "axis units",
              "explicit labelled y minimum when not zero"
            ],
            "limits": [
              "piecewise-linear interpolation only; must not imply a curved model"
            ]
          },
          {
            "id": "FREE_BODY_DIAGRAM",
            "status": "PROPOSED"
          },
          {
            "id": "RAY_DIAGRAM",
            "status": "PROPOSED"
          },
          {
            "id": "CIRCUIT_SCHEMATIC",
            "status": "PROPOSED"
          }
        ],
        "curriculum": {
          "boards": [
            "CBSE"
          ],
          "grades": [
            9,
            10,
            11
          ],
          "tiers": [
            "NOT_IN_JEE",
            "JEE_MAINS",
            "JEE_ADVANCED",
            "BOTH"
          ],
          "binding_authority": "EXACT_REGISTRY_BINDING_REQUIRED",
          "unbound_scope_state": "HELD_INSUFFICIENT_AUTHORITY"
        }
      },
      "gates": [
        {
          "gate_id": "PHY-VEC-SCALAR-VECTOR",
          "title": "Magnitude, vector and signed component",
          "grade": 9,
          "chapter": "Motion",
          "scope_class": "OWNER_EXTENSION",
          "tier": "NOT_IN_JEE",
          "scope_state": "ACTIVE",
          "prerequisites": [],
          "external_prerequisites": [
            "MATH-SIGNED-COORDINATE",
            "MATH-RIGHT-TRIANGLE"
          ],
          "concepts": [
            "A magnitude is a nonnegative length; it carries no direction information.",
            "A component is a signed reading along a declared axis; its sign is direction information, not a defect.",
            "The signed component pair and the magnitude are two descriptions of one vector, not two separate quantities."
          ],
          "misconceptions": [
            "Stating the magnitude fully answers a question about the vector.",
            "A negative component means a negative speed."
          ]
        },
        {
          "gate_id": "PHY-VEC-AXIS-CONVENTION",
          "title": "Axis choice is free, but once declared it fixes every sign",
          "grade": 9,
          "chapter": "Motion",
          "scope_class": "OWNER_EXTENSION",
          "tier": "NOT_IN_JEE",
          "scope_state": "ACTIVE",
          "prerequisites": [
            "PHY-VEC-SCALAR-VECTOR"
          ],
          "external_prerequisites": [],
          "concepts": [
            "The positive direction of each axis is a free declaration, not a property of the physical situation.",
            "Once declared, the convention fixes the sign of every component measured along that axis."
          ],
          "misconceptions": [
            "A component should be made positive because the object is moving forward."
          ]
        },
        {
          "gate_id": "PHY-VEC-SUBTRACTION",
          "title": "Subtraction as addition of the reversed vector",
          "grade": 9,
          "chapter": "Motion",
          "scope_class": "OWNER_EXTENSION",
          "tier": "NOT_IN_JEE",
          "scope_state": "ACTIVE",
          "prerequisites": [
            "PHY-VEC-SCALAR-VECTOR",
            "PHY-VEC-AXIS-CONVENTION"
          ],
          "external_prerequisites": [],
          "concepts": [
            "Subtracting a vector is defined as adding its reverse.",
            "A free vector may be translated without rotation for a tail-to-head construction."
          ],
          "misconceptions": [
            "Vector subtraction means joining the two arrowheads in whichever order looks convenient.",
            "Reversing a vector changes its magnitude."
          ]
        },
        {
          "gate_id": "PHY-REL-POSITION",
          "title": "Position measured from another object at the same instant",
          "grade": 9,
          "chapter": "Motion",
          "scope_class": "OWNER_EXTENSION",
          "tier": "NOT_IN_JEE",
          "scope_state": "ACTIVE",
          "prerequisites": [
            "PHY-VEC-SUBTRACTION"
          ],
          "external_prerequisites": [],
          "concepts": [
            "Relative position compares two positions recorded at the same instant.",
            "Following origin to B to A gives r_A = r_B + r_A/B, from which the subtraction order follows."
          ],
          "misconceptions": [
            "Subtract whichever position is written first in the question."
          ]
        },
        {
          "gate_id": "PHY-REL-VELOCITY",
          "title": "Relative velocity in a plane",
          "grade": 9,
          "chapter": "Motion",
          "scope_class": "OWNER_EXTENSION",
          "tier": "NOT_IN_JEE",
          "scope_state": "ACTIVE",
          "prerequisites": [
            "PHY-REL-POSITION"
          ],
          "external_prerequisites": [],
          "concepts": [
            "Relative velocity compares how one simultaneous separation changes over one shared time interval.",
            "For constant velocities the relative velocity is the vector difference of common-frame velocities."
          ],
          "misconceptions": [
            "Subtracting the two speeds always gives the relative speed."
          ]
        },
        {
          "gate_id": "PHY-REL-OBSERVER-REVERSAL",
          "title": "Reversing the observer reverses the relative vector",
          "grade": 9,
          "chapter": "Motion",
          "scope_class": "OWNER_EXTENSION",
          "tier": "NOT_IN_JEE",
          "scope_state": "ACTIVE",
          "prerequisites": [
            "PHY-REL-VELOCITY"
          ],
          "external_prerequisites": [],
          "concepts": [
            "The relative-velocity relation is antisymmetric in its two objects.",
            "Reversal changes direction but not magnitude."
          ],
          "misconceptions": [
            "A correct length is enough for a correct relative-velocity answer."
          ]
        }
      ],
      "buckets": [
        {
          "id": "BUCKET-RELATIVE-MOTION",
          "title": "Relative velocity in a plane",
          "topic": "Motion in two dimensions",
          "badge": "HARD",
          "status": "CANDIDATE",
          "prerequisites": [
            "CAP-SIGNED-PAIR",
            "BUCKET-VECTOR-REPRESENTATION"
          ],
          "curriculum": [
            {
              "board": "CBSE",
              "grade": 9,
              "academic_year": "2026-27",
              "track": "ADVANCED",
              "scope_class": "OWNER_EXTENSION",
              "source_ref": "SRC-CBSE-ADV",
              "locator": "Chapter 2 for background only; quantitative vector relative velocity is treated as extension",
              "mapping_status": "CANDIDATE"
            }
          ],
          "microtopics": [
            {
              "id": "MIC-SAME-TIME",
              "title": "Position measured from the other object",
              "badge": "HARD",
              "status": "CANDIDATE",
              "badge_reason": "Observer order and common time are easily hidden by a memorized formula.",
              "entry_assumptions": [
                "Signed coordinate-pair arithmetic is available or bridged."
              ],
              "inferential_jump": "Replace two positions from an origin by the displacement from B to A.",
              "teaching_path": [
                {
                  "action": "Follow the path origin → B → A.",
                  "why_valid": "Vector displacements add along consecutive paths.",
                  "output": "r_A = r_B + r_A/B"
                },
                {
                  "action": "Subtract r_B from both sides.",
                  "why_valid": "Apply the same vector operation to both sides.",
                  "output": "r_A/B = r_A - r_B"
                }
              ],
              "misconceptions": [
                {
                  "wrong_idea": "Subtract whichever coordinate appears first in the question.",
                  "diagnostic_prompt": "Which displacement carries you from B to A?",
                  "repair": "Draw origin → B → A and reconstruct r_A = r_B + r_A/B before subtracting."
                }
              ],
              "exit_task": {
                "prompt": "At one instant A is at (7,2) m and B at (3,5) m. Give A relative to B and explain the signs.",
                "source_ref": "SRC-AUTHOR",
                "answer": {
                  "kind": "MODEL_RESPONSE",
                  "summary": "(4,-3) m: 4 m east and 3 m south from B.",
                  "reasoning": [
                    "Subtract the same-time coordinates of B from A.",
                    "The negative north component means south."
                  ],
                  "check": "Add (4,-3) to B=(3,5); recover A=(7,2).",
                  "acceptable_alternatives": [],
                  "subpart_answers": [],
                  "verification_status": "CHECKED_BY_AUTHOR"
                }
              },
              "prerequisites": [
                "CAP-SIGNED-PAIR"
              ]
            },
            {
              "id": "MIC-COMMON-INTERVAL",
              "title": "From relative position to relative velocity",
              "badge": "HARD",
              "status": "CANDIDATE",
              "badge_reason": "The student must connect two same-time position statements to one common interval rather than memorize a subtraction rule.",
              "entry_assumptions": [
                "Can construct relative position and interpret displacement over time."
              ],
              "inferential_jump": "Subtract two relative-position equations before dividing by a common time interval.",
              "teaching_path": [
                {
                  "action": "Write relative position at t1 and t2.",
                  "why_valid": "Apply the same relation at both instants.",
                  "output": "r_A/B(t2) - r_A/B(t1) = [r_A(t2)-r_A(t1)] - [r_B(t2)-r_B(t1)]"
                },
                {
                  "action": "Group the displacement changes.",
                  "why_valid": "Vector subtraction distributes through the two same-time equations.",
                  "output": "Delta r_A/B = Delta r_A - Delta r_B"
                },
                {
                  "action": "Divide each term by the same nonzero Delta t.",
                  "why_valid": "Each quotient is average velocity over that interval.",
                  "output": "vbar_A/B = vbar_A - vbar_B"
                },
                {
                  "action": "For this constant-velocity teaching case, use v for each constant average.",
                  "why_valid": "No instantaneous calculus limit is needed in this case.",
                  "output": "v_A/B = v_A - v_B"
                }
              ],
              "misconceptions": [
                {
                  "wrong_idea": "Subtracting the two speeds always gives relative speed.",
                  "diagnostic_prompt": "If one object moves east and the other north, do their directions disappear?",
                  "repair": "Compute signed vector components first, then take the magnitude if requested."
                }
              ],
              "exit_task": {
                "prompt": "Why must both displacement changes be divided by the same time interval in this derivation?",
                "source_ref": "SRC-AUTHOR",
                "answer": {
                  "kind": "MODEL_RESPONSE",
                  "summary": "The relation compares how the simultaneous separation changes over one shared interval.",
                  "reasoning": [
                    "Write the positions of both objects at t1 and again at t2.",
                    "Subtract those two relative positions.",
                    "Different intervals describe different displacement changes and do not form this comparison."
                  ],
                  "check": "For equal constant velocity vectors, the separation must stay constant.",
                  "acceptable_alternatives": [],
                  "subpart_answers": [],
                  "verification_status": "CHECKED_BY_AUTHOR"
                }
              },
              "prerequisites": [
                "MIC-SAME-TIME"
              ]
            },
            {
              "id": "MIC-GEOMETRIC-CHECK",
              "title": "Check direction, magnitude and observer reversal",
              "badge": "HARD",
              "status": "CANDIDATE",
              "badge_reason": "Correct arithmetic can conceal an incorrect vector construction or frame interpretation.",
              "entry_assumptions": [
                "Can subtract velocity components; a magnitude calculation requires a reviewed right-triangle bridge."
              ],
              "inferential_jump": "Reconcile the algebraic result with reversal of the observer vector in a geometric construction.",
              "teaching_path": [
                {
                  "action": "Reverse v_B.",
                  "why_valid": "Subtraction is addition of the opposite vector.",
                  "output": "-v_B has the same magnitude and opposite direction."
                },
                {
                  "action": "Add v_A and -v_B tail to head.",
                  "why_valid": "Free vectors may be translated without rotation.",
                  "output": "Resultant v_A/B."
                },
                {
                  "action": "Compare components and reverse the observer order.",
                  "why_valid": "v_B/A = -(v_A/B).",
                  "output": "Opposite vectors have equal magnitudes."
                }
              ],
              "misconceptions": [
                {
                  "wrong_idea": "A correct length is enough for a correct vector answer.",
                  "diagnostic_prompt": "Would the same arrow reversed describe the same observer statement?",
                  "repair": "Name the observer, label both components and inspect the direction before taking a magnitude."
                }
              ],
              "exit_task": {
                "prompt": "If v_A/B points southeast, what direction does v_B/A point, and what happens to its magnitude?",
                "source_ref": "SRC-AUTHOR",
                "answer": {
                  "kind": "MODEL_RESPONSE",
                  "summary": "Northwest, with the same magnitude.",
                  "reasoning": [
                    "Swap the subtraction order.",
                    "Every component changes sign."
                  ],
                  "check": "Adding the two relative vectors gives zero.",
                  "acceptable_alternatives": [],
                  "subpart_answers": [],
                  "verification_status": "CHECKED_BY_AUTHOR"
                }
              },
              "prerequisites": [
                "MIC-COMMON-INTERVAL",
                "MIC-GRAPHICAL-SUBTRACTION"
              ]
            },
            {
              "id": "MIC-FRAME-QUALIFICATION-BOUNDARY",
              "title": "When the simple v_A/B = v_A - v_B relation needs frame qualification (research-boundary note)",
              "badge": "HARD",
              "status": "CANDIDATE",
              "badge_reason": "Not a Grade 9 assessment badge: this is a RESEARCH-depth boundary note, included only to show where the taught relation stops applying.",
              "entry_assumptions": [
                "Has completed MIC-GEOMETRIC-CHECK and accepts v_A/B = v_A - v_B for translating, nonrotating frames."
              ],
              "inferential_jump": "Recognise that the simple subtraction relation assumes both frames are nonrotating and non-relativistic; naming when it needs qualification is itself the (bounded) research task, not deriving the replacement mathematics.",
              "teaching_path": [
                {
                  "action": "Restate the two conditions already attached to REL-RELATIVE-VELOCITY: parallel nonrotating axes, classical (non-relativistic) speeds.",
                  "why_valid": "Those conditions were declared, not incidental, when the relation was derived.",
                  "output": "The relation is conditional, not universal."
                },
                {
                  "action": "Name, without deriving, the two regimes where each condition can fail: a rotating reference frame (needs Coriolis/centrifugal terms) and speeds approaching light speed (needs relativistic velocity addition).",
                  "why_valid": "Naming the failure regime is a defensible research-boundary claim; deriving the replacement transformation is graduate-level and explicitly out of scope here.",
                  "output": "Two named boundaries, no new formula taught."
                },
                {
                  "action": "State that this note is excluded from Grade 9 assessment claims and is not required for MIC-GEOMETRIC-CHECK's exit task.",
                  "why_valid": "Research-depth material is segregated from exam scope (TOPIC_WORKFLOW.md); a badge cannot be raised to smuggle in graduate prerequisites.",
                  "output": "Explicit non-assessment status."
                }
              ],
              "misconceptions": [
                {
                  "wrong_idea": "Since the school formula is 'wrong' in general, it should not be taught or trusted at all.",
                  "diagnostic_prompt": "Does a merry-go-round or a near-light-speed spacecraft appear anywhere in the Grade 9 assessment scope?",
                  "repair": "A model's stated domain of validity is what makes it correct within that domain; the Grade 9 translating-frame case is exactly where the taught relation applies."
                }
              ],
              "exit_task": {
                "prompt": "Name (without deriving) one situation where v_A/B = v_A - v_B would need an additional term, and state whether that situation is in the Grade 9 assessment scope.",
                "source_ref": "SRC-AUTHOR",
                "answer": {
                  "kind": "MODEL_RESPONSE",
                  "summary": "A rotating reference frame (e.g. observations made from a spinning platform) needs an additional Coriolis-type term; this is outside the Grade 9 assessment scope.",
                  "reasoning": [
                    "The derivation in MIC-COMMON-INTERVAL assumed parallel, nonrotating axes at every instant.",
                    "A rotating frame violates that assumption, so the simple difference no longer accounts for the frame's own rotation."
                  ],
                  "check": "The excluded-topics list for this run already names 'Rotating frames and Coriolis terms' as out of scope, consistent with this boundary note.",
                  "acceptable_alternatives": [
                    "Relativistic velocity addition, for speeds approaching c, is also acceptable."
                  ],
                  "subpart_answers": [],
                  "verification_status": "CHECKED_BY_AUTHOR"
                }
              },
              "prerequisites": [
                "MIC-GEOMETRIC-CHECK"
              ]
            }
          ],
          "relations": [
            {
              "id": "REL-RELATIVE-POSITION",
              "expression": "r_A/B(t) = r_A(t) - r_B(t)",
              "meaning": "The displacement from B to A is what remains after subtracting the common-origin position of B.",
              "conditions": [
                "Use the same observation times and a common time interval.",
                "Express all vectors along parallel, nonrotating Cartesian axes.",
                "Use a classical kinematic model; do not apply relativistic velocity addition."
              ]
            },
            {
              "id": "REL-RELATIVE-VELOCITY",
              "expression": "v_A/B = v_A - v_B",
              "meaning": "For constant velocities, relative position changes at the difference of their common-frame velocity vectors; the same finite-interval derivation also gives average relative velocity.",
              "conditions": [
                "Use the same observation times and a common time interval.",
                "Express all vectors along parallel, nonrotating Cartesian axes.",
                "Use a classical kinematic model; do not apply relativistic velocity addition."
              ]
            },
            {
              "id": "REL-VECTOR-SUBTRACTION",
              "expression": "P - Q = P + (-Q)",
              "meaning": "Subtracting a vector means adding its reverse; component-wise this is (P-Q)_x = P_x - Q_x and (P-Q)_y = P_y - Q_y.",
              "conditions": [
                "P and Q are expressed along the same declared axes.",
                "Free vectors may be translated without rotation for the graphical construction."
              ]
            }
          ],
          "questions": [
            {
              "id": "Q-AUTHOR-REL-01",
              "stem": "In a common east/north frame, A moves at (6,0) m/s and B at (0,8) m/s. Find the velocity of A relative to B. State its direction and magnitude.",
              "origin": "AUTHORED",
              "answer": "(6,-8) m/s, southeast; magnitude 10 m/s."
            }
          ],
          "capabilities": [
            {
              "id": "CAP-GRAPHICAL-SUBTRACT",
              "action": "Construct the graphical subtraction of two vectors as addition of the reversed second vector.",
              "provider": null,
              "acceptance": "CANDIDATE"
            },
            {
              "id": "CAP-RELATIVE-V",
              "action": "Obtain relative velocity from same-time positions over one common interval.",
              "provider": null,
              "acceptance": "CANDIDATE"
            },
            {
              "id": "CAP-RIGHT-TRIANGLE",
              "action": "Obtain the hypotenuse from two perpendicular component lengths.",
              "provider": "Mathematics",
              "acceptance": "PROVIDER_REVIEW_REQUIRED"
            },
            {
              "id": "CAP-RIGHT-TRIANGLE-BRIDGE",
              "action": "Obtain the hypotenuse length from two perpendicular leg lengths.",
              "provider": "Mathematics",
              "acceptance": "PROVIDER_REVIEW_REQUIRED"
            },
            {
              "id": "CAP-SAME-TIME",
              "action": "Construct the position of A relative to B at the same instant.",
              "provider": null,
              "acceptance": "CANDIDATE"
            },
            {
              "id": "CAP-SIGNED-PAIR",
              "action": "Read signed coordinates and subtract two coordinate pairs.",
              "provider": "Mathematics",
              "acceptance": "PROVIDER_REVIEW_REQUIRED"
            },
            {
              "id": "CAP-SIGNED-PAIR-BRIDGE",
              "action": "Read signed coordinates on an axis and subtract two coordinate values, keeping the sign.",
              "provider": "Mathematics",
              "acceptance": "PROVIDER_REVIEW_REQUIRED"
            },
            {
              "id": "CAP-VECTOR-CHECK",
              "action": "Reconcile a relative-velocity vector with components and limiting cases.",
              "provider": null,
              "acceptance": "CANDIDATE"
            },
            {
              "id": "CAP-VECTOR-VS-SCALAR",
              "action": "Distinguish a scalar magnitude from a vector, and read a vector's signed components along declared axes.",
              "provider": null,
              "acceptance": "CANDIDATE"
            }
          ],
          "record_count": 33,
          "compile_preview": {
            "compilable": true,
            "supported_products": [
              "CORE1A",
              "CORE1B",
              "CORE2A"
            ],
            "atoms": 17,
            "questions": 1,
            "obligations": 4,
            "authoring_requirements": [
              {
                "kind": "PRODUCT_UNSUPPORTED",
                "core": "CORE2B",
                "detail": "the library holds no question exposed to this product for this bucket"
              },
              {
                "kind": "PROSE_AUTHORING",
                "core": "CORE1A",
                "detail": "blocks carry library-held teaching text; connecting narrative, worked examples and figure scenes still require authoring"
              },
              {
                "kind": "PROSE_AUTHORING",
                "core": "CORE1B",
                "detail": "blocks carry library-held teaching text; connecting narrative, worked examples and figure scenes still require authoring"
              },
              {
                "kind": "FIGURE_AUTHORING",
                "core": "CORE2A",
                "detail": "the library describes representation requirements but holds no figure scene instances; scenes must be authored"
              }
            ]
          }
        },
        {
          "id": "BUCKET-VECTOR-REPRESENTATION",
          "title": "Vector representation and subtraction",
          "topic": "Motion in two dimensions",
          "badge": "MEDIUM",
          "status": "CANDIDATE",
          "prerequisites": [
            "CAP-SIGNED-PAIR-BRIDGE"
          ],
          "curriculum": [
            {
              "board": "CBSE",
              "grade": 9,
              "academic_year": "2026-27",
              "track": "ADVANCED",
              "scope_class": "OWNER_EXTENSION",
              "source_ref": "SRC-CBSE-ADV",
              "locator": "Chapter 2 for background only; quantitative vector construction/subtraction is treated as extension",
              "mapping_status": "CANDIDATE"
            }
          ],
          "microtopics": [
            {
              "id": "MIC-VECTOR-VS-SCALAR",
              "title": "Magnitude, vector and signed component",
              "badge": "MEDIUM",
              "status": "CANDIDATE",
              "badge_reason": "The distinction is easy to state and easy to blur under time pressure, once negative components appear.",
              "entry_assumptions": [
                "Signed coordinate subtraction on one axis is available or bridged."
              ],
              "inferential_jump": "See a nonnegative speed/magnitude and a pair of signed components as two different descriptions of one physical vector, not two separate quantities.",
              "teaching_path": [
                {
                  "action": "Name the frame and the two perpendicular axes before reading any component.",
                  "why_valid": "A signed component has no meaning without a declared positive direction.",
                  "output": "Declared frame: e.g. east positive x, north positive y."
                },
                {
                  "action": "Read each component with its sign from the declared axes.",
                  "why_valid": "The sign is the axis reading itself, not an adjustment made afterwards.",
                  "output": "w = (3, 4) m/s means 3 m/s east and 4 m/s north."
                },
                {
                  "action": "Apply the right-triangle bridge to the two component magnitudes.",
                  "why_valid": "Perpendicular components are legs of a right triangle whose hypotenuse is the vector length.",
                  "output": "speed = sqrt(3^2+4^2) = 5 m/s"
                },
                {
                  "action": "State the magnitude as nonnegative and keep the signed components separately for direction.",
                  "why_valid": "Squaring erases sign, so recovering direction needs the original signed pair, not the magnitude.",
                  "output": "5 m/s is the speed; (3,4) m/s is still needed to say which way."
                }
              ],
              "misconceptions": [
                {
                  "wrong_idea": "The magnitude and the vector are the same thing, so stating '5 m/s' fully answers a direction question.",
                  "diagnostic_prompt": "Two vectors, (3,4) and (4,3) m/s, have the same magnitude. Do they point the same way?",
                  "repair": "Recompute both magnitudes (both 5 m/s) then compare the signed components directly; equal magnitude does not mean equal vector."
                },
                {
                  "wrong_idea": "A negative component means the object is slow or the quantity is 'negative speed'.",
                  "diagnostic_prompt": "If the y-component is -4 m/s, is the speed negative?",
                  "repair": "Separate the signed component (direction information) from the magnitude (always taken nonnegative after squaring)."
                }
              ],
              "exit_task": {
                "prompt": "A vector has components (-3, 4) m/s. State its magnitude and describe its direction in words.",
                "source_ref": "SRC-AUTHOR-VEC",
                "answer": {
                  "kind": "MODEL_RESPONSE",
                  "summary": "Magnitude 5 m/s; the vector points into the quadrant that is left (negative x) and up (positive y).",
                  "reasoning": [
                    "Apply the right-triangle bridge: sqrt((-3)^2+4^2) = sqrt(25) = 5 m/s.",
                    "Keep the original signs for direction: negative x-component, positive y-component."
                  ],
                  "check": "Reversing both signs, (3,-4), would give the same magnitude but the opposite direction.",
                  "acceptable_alternatives": [],
                  "subpart_answers": [],
                  "verification_status": "CHECKED_BY_AUTHOR"
                }
              },
              "prerequisites": [
                "CAP-SIGNED-PAIR-BRIDGE"
              ]
            },
            {
              "id": "MIC-SIGNED-COMPONENT",
              "title": "Choosing axes and keeping components signed",
              "badge": "MEDIUM",
              "status": "CANDIDATE",
              "badge_reason": "Axis choice feels arbitrary to a new learner, so students often silently drop or flip a sign when the story changes.",
              "entry_assumptions": [
                "Can identify a vector's components once axes are declared."
              ],
              "inferential_jump": "Recognise that the axis choice is a free, declared decision, but once declared, every component's sign is fixed by it — not by the physical 'niceness' of the described motion.",
              "teaching_path": [
                {
                  "action": "Declare positive directions for both axes explicitly before reading any component.",
                  "why_valid": "A component's sign is only meaningful relative to a stated positive direction.",
                  "output": "e.g. 'east and north positive' stated once for the whole problem."
                },
                {
                  "action": "Re-express the same vector under a reversed axis convention.",
                  "why_valid": "Reversing a declared positive direction negates every component measured along it, without changing the physical vector.",
                  "output": "w=(3,4) m/s under east/north-positive becomes (-3,4) m/s if x is redeclared west-positive."
                },
                {
                  "action": "Confirm the magnitude is unchanged by the axis convention.",
                  "why_valid": "The right-triangle bridge only uses squared components, and squaring removes the sign flip.",
                  "output": "Both conventions give magnitude 5 m/s."
                }
              ],
              "misconceptions": [
                {
                  "wrong_idea": "A component should be made positive because the object is 'moving forward'.",
                  "diagnostic_prompt": "If east is declared positive and the object moves west, is the x-component positive or negative?",
                  "repair": "The sign follows the declared axis only; 'forward' is not itself an axis direction unless it was declared as one."
                }
              ],
              "exit_task": {
                "prompt": "Under 'north positive, east positive', a vector is (5,-2) m/s. State it again under 'south positive, east positive', and explain why the magnitude does not change.",
                "source_ref": "SRC-AUTHOR-VEC",
                "answer": {
                  "kind": "MODEL_RESPONSE",
                  "summary": "(5, 2) m/s under the new convention; magnitude stays sqrt(25+4) both times.",
                  "reasoning": [
                    "Only the axis whose positive direction was reversed changes sign; east stays as declared.",
                    "The right-triangle bridge squares both components, so a sign flip on one component does not change the magnitude."
                  ],
                  "check": "Re-declare the axis back to the original convention and confirm (5,-2) is recovered.",
                  "acceptable_alternatives": [],
                  "subpart_answers": [],
                  "verification_status": "CHECKED_BY_AUTHOR"
                }
              },
              "prerequisites": [
                "MIC-VECTOR-VS-SCALAR"
              ]
            },
            {
              "id": "MIC-GRAPHICAL-SUBTRACTION",
              "title": "Subtraction as addition of the reversed vector",
              "badge": "MEDIUM",
              "status": "CANDIDATE",
              "badge_reason": "The reverse-then-add construction is a genuine model shift from ordinary addition, even though the component arithmetic looks similar.",
              "entry_assumptions": [
                "Can read signed components and knows a vector's magnitude is not its direction."
              ],
              "inferential_jump": "See P - Q as P + (-Q): reverse Q's arrowhead without changing its length, then apply tail-to-head addition.",
              "teaching_path": [
                {
                  "action": "Reverse Q.",
                  "why_valid": "Negating a vector keeps its length and flips both signed components.",
                  "output": "-Q has the same magnitude as Q and the opposite direction."
                },
                {
                  "action": "Translate -Q to the head of P without rotating it.",
                  "why_valid": "A free vector's meaning depends only on length and direction, not on where it is drawn.",
                  "output": "-Q placed tail-to-head with P."
                },
                {
                  "action": "Draw the resultant from the tail of P to the head of the translated -Q.",
                  "why_valid": "Tail-to-head addition gives the vector sum, here P + (-Q) = P - Q.",
                  "output": "Resultant vector P-Q."
                },
                {
                  "action": "Reconcile the drawn resultant with the signed-component subtraction.",
                  "why_valid": "Both the graphical and component routes compute the same operation and must agree.",
                  "output": "Component check: (P-Q)_x = P_x-Q_x, (P-Q)_y = P_y-Q_y."
                }
              ],
              "misconceptions": [
                {
                  "wrong_idea": "Vector subtraction means drawing both vectors from the same origin and connecting their two tips in whichever order looks right.",
                  "diagnostic_prompt": "Which endpoint does the subtraction arrow start from: the tip of P or the tip of Q?",
                  "repair": "Perform the explicit reverse-then-add construction (GS-1 to GS-3); the two-tips shortcut hides the observer order and is easy to reverse by mistake."
                },
                {
                  "wrong_idea": "Reversing a vector changes its magnitude.",
                  "diagnostic_prompt": "Does an arrow get longer or shorter when you flip it end for end?",
                  "repair": "Reversal only negates the signed components; the right-triangle bridge uses their squares, so the magnitude is unchanged."
                }
              ],
              "exit_task": {
                "prompt": "In a common east/north frame, P = (6,0) m/s and Q = (0,8) m/s. Construct P - Q graphically and state the resultant's components and magnitude.",
                "source_ref": "SRC-AUTHOR-VEC",
                "answer": {
                  "kind": "MODEL_RESPONSE",
                  "summary": "P-Q = (6,-8) m/s, magnitude 10 m/s.",
                  "reasoning": [
                    "Reverse Q to get -Q = (0,-8) m/s.",
                    "Add P and -Q tail-to-head: (6+0, 0+(-8)) = (6,-8) m/s.",
                    "Right-triangle bridge: sqrt(6^2+8^2) = sqrt(100) = 10 m/s."
                  ],
                  "check": "Component subtraction directly: (6-0, 0-8) = (6,-8) m/s, matching the graphical construction.",
                  "acceptable_alternatives": [],
                  "subpart_answers": [],
                  "verification_status": "CHECKED_BY_AUTHOR"
                }
              },
              "prerequisites": [
                "MIC-VECTOR-VS-SCALAR",
                "MIC-SIGNED-COMPONENT"
              ]
            }
          ],
          "relations": [
            {
              "id": "REL-VECTOR-SUBTRACTION",
              "expression": "P - Q = P + (-Q)",
              "meaning": "Subtracting a vector means adding its reverse; component-wise this is (P-Q)_x = P_x - Q_x and (P-Q)_y = P_y - Q_y.",
              "conditions": [
                "P and Q are expressed along the same declared axes.",
                "Free vectors may be translated without rotation for the graphical construction."
              ]
            }
          ],
          "questions": [],
          "capabilities": [
            {
              "id": "CAP-GRAPHICAL-SUBTRACT",
              "action": "Construct the graphical subtraction of two vectors as addition of the reversed second vector.",
              "provider": null,
              "acceptance": "CANDIDATE"
            },
            {
              "id": "CAP-RIGHT-TRIANGLE-BRIDGE",
              "action": "Obtain the hypotenuse length from two perpendicular leg lengths.",
              "provider": "Mathematics",
              "acceptance": "PROVIDER_REVIEW_REQUIRED"
            },
            {
              "id": "CAP-SIGNED-PAIR-BRIDGE",
              "action": "Read signed coordinates on an axis and subtract two coordinate values, keeping the sign.",
              "provider": "Mathematics",
              "acceptance": "PROVIDER_REVIEW_REQUIRED"
            },
            {
              "id": "CAP-VECTOR-VS-SCALAR",
              "action": "Distinguish a scalar magnitude from a vector, and read a vector's signed components along declared axes.",
              "provider": null,
              "acceptance": "CANDIDATE"
            }
          ],
          "record_count": 17,
          "compile_preview": {
            "compilable": false,
            "code": "LIBRARY_SUPPORTS_NO_PRODUCT",
            "detail": "BUCKET-VECTOR-REPRESENTATION"
          }
        }
      ],
      "packages": [
        {
          "package_id": "LIB-PHY-RELATIVE-MOTION-SEED",
          "status": "CANDIDATE",
          "admitted": true
        },
        {
          "package_id": "LIB-PHY-VECTOR-REPRESENTATION-SEED",
          "status": "CANDIDATE",
          "admitted": true
        }
      ],
      "library_available": true
    }
  }
};
